dependencies:
 - python
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - requests
 - pandas
 - seaborn
 - click
 - openpyxl
 - tensorflow
 - keras
 - pip:
   - setuptools
   - watermark
   - pytest
   - SpeechRecognition
   - python_speech_features
   - pyaudio
   - beautifulsoup4
   - google
   - PyHamcrest
   - cython
   - html5lib
   - selenium